<?php
/**
 * Build Asset File Generator
 *
 * This script generates the admin-app.asset.php file after building.
 * Run this after `npm run build` to update the asset file.
 */

$build_dir = __DIR__ . '/../build';
$asset_file = $build_dir . '/admin-app.asset.php';

// Check if build files exist
if ( ! file_exists( $build_dir . '/admin-app.js' ) ) {
	echo "Error: Build files not found. Run 'npm run build' first.\n";
	exit( 1 );
}

// Read package.json to get version
$package_json = json_decode( file_get_contents( __DIR__ . '/../package.json' ), true );
$version = $package_json['version'] ?? '1.0.0';

// Generate asset file
$asset_content = "<?php\n";
$asset_content .= "/**\n";
$asset_content .= " * Admin App Asset File\n";
$asset_content .= " *\n";
$asset_content .= " * This file is auto-generated by the build process.\n";
$asset_content .= " */\n\n";
$asset_content .= "return array(\n";
$asset_content .= "\t'dependencies' => array(\n";
$asset_content .= "\t\t'react',\n";
$asset_content .= "\t\t'react-dom',\n";
$asset_content .= "\t\t'wp-api-fetch',\n";
$asset_content .= "\t),\n";
$asset_content .= "\t'version'      => '" . $version . "',\n";
$asset_content .= ");\n";

file_put_contents( $asset_file, $asset_content );
echo "Asset file generated successfully!\n";

